Backport upstream fix for longer openscap rules to 2.7
Backport upstream 05553d6aabfac886f8d375a9717392015d207e8d 487a450cfd55f60d1adc3e56afdfddb4de0f64d9

1646942 - openscap rule identifiers can exceed 100 chars

    fixing ISE on /rhn/systems/details/audit/ListScap.do
    2018-11-06 12:09:29,023 [TP-Processor7] ERROR com.redhat.rhn.frontend.servlets.SessionFilter - Error during transaction. Rolling back javax.el.ELException: Error reading 'diffIcon' on type com.redhat.rhn.frontend.dto.XccdfTestResultDto
    ...
    Caused by:
    java.lang.IllegalArgumentException: Multiple rules with idref=xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_by_handle_at_o_...

1646942 - update existing data

Orabug: 29759777

Signed-off-by: Laurence Rochfort <laurence.rochfort@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>