Fix cStringIO/StringIO import trap ordering.
The cStringIO/StringIO import trap always imports io.StringIO
regardless of the Python version. On Python 2.x this causes an
unhandled TypeError that prevents a traceback being logged during an
error.

This typically manifests as the following error from osa-dispatcher,
preventing it from registering new/updated clients.

ERROR: unhandled exception occurred: (unicode argument expected, got 'str')

OraBug: 28528975

Signed-off-by: Laurence Rochfort <laurence.rochfort@oracle.com>
Reviewed-by: Yinbo Wang <yinbo.wang@oracle.com>